<template>
  <v-app id="content">
    <v-toolbar app id="toolbar">
      <v-toolbar-title class="headline text-uppercase">
        <span>Robot</span>
        <span class="font-weight-light">Car</span>
      </v-toolbar-title>

      <v-spacer></v-spacer>
      <v-btn color="primary" dark @click.stop="dialog = true">Anslutningsalternativ</v-btn>
      <v-btn target="_blank" @click="Switch=!Switch">
        <span v-if="Switch!==true" class="mr-2">Buttons 1</span>
        <span v-else class="mr-2">Buttons 2</span>
      </v-btn>
    </v-toolbar>

    <v-content>
      <v-row align="center" justify="center">
        <v-dialog v-model="dialog" max-width="290" height="290">
          <v-card>
            <v-card-title class="headline">Anslutning till Server</v-card-title>

            <v-card-text style="height: 300px;">
              <v-text-field v-model="name" label="Name" filled></v-text-field>

              <v-text-field v-model="password" label="MQTT Password" filled></v-text-field>

              <v-text-field v-model="port" label="Port" filled></v-text-field>
              <v-text-field v-model="adress" label="Adress" filled></v-text-field>
            </v-card-text>

            <v-card-actions>
              <v-spacer></v-spacer>

              <v-btn color="green darken-1" text @click="save()">Spara</v-btn>
            </v-card-actions>
          </v-card>
        </v-dialog>

        <div>
          <Logger />

          <Buttons v-if="Switch" />
          <Buttons2 v-else />
        </div>
      </v-row>
    </v-content>
  </v-app>
</template>

<script>
import Buttons2 from "./components/Buttonsv2";
import Buttons from "./components/Buttons";
import Logger from "./components/Logger";

export default {
  name: "App",
  components: {
    Buttons,
    Buttons2,
    Logger
  },
  data() {
    return {
      Switch: false,
      dialog: false,
      name: "",
      password: "",
      port: "",
      adress: ""
    };
  },
  created() {
    let User = this.$store.getters.GetUser;
    this.name = User.name;
    this.password = User.password;
    this.port = User.port;
    this.adress = User.adress;
  },

  methods: {
    save() {
      let User = {
        name: this.name,
        password: this.password,
        port: this.port,
        adress: this.adress
      };

      this.$store.dispatch("Save", User);

      this.dialog = false;
    }
  },
  computed: {}
};
</script>
<style scoped>
.img {
  width: 40%;
  height: 40%;
  margin: auto;
  padding: 10px;
}
#logger {
  /* position: fixed;
  bottom: 0;
  right: 0; */
  width: 300px;
  height: 300px;
  border: black dotted 2px;

  word-wrap: break-word;
}

/* https://beautifuldingbats.com/pattern-generator/ https://css-tricks.com/using-svg/ */
#toolbar {
  background-image: url("data:image/svg+xml,%3C!-- SVG Pattern generated by 𝕭𝖊𝖆𝖚𝖙𝖎𝖋𝖚𝖑 𝕯𝖎𝖓𝖌𝖇𝖆𝖙𝖘 --%3E%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='100%25' height='100%25'%3E%3Cdefs%3E%3Cpattern id='pattern' width='30' height='30' viewBox='0 0 40 40' patternUnits='userSpaceOnUse' patternTransform='rotate(35)'%3E%3Crect id='pattern-background' x='0' y='0' width='400%25' height='400%25' fill='%2363e6be'/%3E%3C!----%3E%3C!----%3E%3Cpath d='M0,20 h10 v-16 h-10 z' fill='%231E88E5' shape-rendering='auto' stroke-width='0' stroke='%231E88E5' stroke-linejoin='round'/%3E%3Cpath d='M20,20 h10 v-16 h-10 z' fill='%231E88E5' shape-rendering='auto' stroke-width='0' stroke='%231E88E5' stroke-linejoin='round'/%3E%3C!----%3E%3C!----%3E%3Cpath d='M10,20 h10 v-20 h-10 z' fill='%23339af0' shape-rendering='auto' stroke-width='0' stroke='%23339af0' stroke-linejoin='round'/%3E%3Cpath d='M30,20 h10 v-20 h-10 z' fill='%23339af0' shape-rendering='auto' stroke-width='0' stroke='%23339af0' stroke-linejoin='round'/%3E%3C/pattern%3E%3C/defs%3E%3Crect fill='url(%23pattern)' height='100%25' width='100%25' y='0' x='0'/%3E%3C/svg%3E");
}
#content {
  background-image: url("data:image/svg+xml,%3C!-- SVG Pattern generated by 𝕭𝖊𝖆𝖚𝖙𝖎𝖋𝖚𝖑 𝕯𝖎𝖓𝖌𝖇𝖆𝖙𝖘 --%3E%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='100%25' height='100%25'%3E%3Cdefs%3E%3Cpattern id='pattern' width='29' height='29' viewBox='0 0 40 40' patternUnits='userSpaceOnUse' patternTransform='rotate(29)'%3E%3Crect id='pattern-background' x='0' y='0' width='400%25' height='400%25' fill='%2369db7c'/%3E%3Ccircle cx='0' cy='0' r='16.2' fill='%23ff6b6b' stroke='%23ff6b6b' stroke-width='0'/%3E%3Ccircle cx='40' cy='40' r='28.8' fill='%23ff6b6b' stroke='%23ff6b6b' stroke-width='0'/%3E%3C!----%3E%3C!----%3E%3C!----%3E%3C!----%3E%3Cpath d='M 20 4 a 16 16 0 0 0 0 32 a 16 16 0 0 0 0 -32 z M 0 0 h 40 v 40 h -40 z' fill='%23f783ac' stroke-width='0' stroke='%23f783ac' shape-rendering='auto' stroke-linejoin='round'/%3E%3C/pattern%3E%3C/defs%3E%3Crect fill='url(%23pattern)' height='100%25' width='100%25' y='0' x='0'/%3E%3C/svg%3E");
}
</style>
